### ISSUE TITLE
Suggestion: Allow the user to configure what block something burns into

### ISSUE THREAD

**Issue by Snorps** [Laike-Endaril/Controlled-Burn#1]
So say grass could be configured to be flammable, but instead of replacing to air as is the default, it replaced to dirt.

Great mod btw ^^ really like being able to put the danger back into wildfires

**Comment by Laike-Endaril** [comment]
Oh crap, someone asked me for this a while back and I completely forgot...I've been pretty busy lately.

Yes, this should be doable, I believe.  No immediate ETA though; I have a lot on my plate (mostly on some stuff that isn't released on curseforge yet)

**Comment by Laike-Endaril** [comment]
This is now implemented in the latest version (1.12.2.017)
