### ISSUE TITLE
Suggestion: Option to blacklist all blocks from burning except those in a separate with list.

### ISSUE THREAD

**Issue by SirAron111** [Laike-Endaril/Controlled-Burn#2]
Suggestion: Option to blacklist all blocks from burning except those in a separate with list.

I like the mod its better than turning dofiretick to false via game rules since flames actually don’t stay around forever. Would it be possible to make it so I can set certain blocks like wood or trees etc dyntrees and so on in a withlist and have all other blocks blacklisted from catching fire if they aren’t in the list? Withlist would have netherack and bedrock as default.

Because I like it when trees and wood burns but I don’t like it when suddenly stones and grass and all that does the same! But turning do fire tick to false simply just makes the fire stay around forever (really annoying when an ice and fire dragon flames everything to the ground)

**Comment by Laike-Endaril** [comment]
It sounds like you want a whitelist?  Ie. "only these blocks can burn"?

**Comment by Laike-Endaril** [comment]
Ah, just now noticed that reaction there...

Hmm...you can already define new flammability values to blocks, but it would be very annoying and tedious to have to do that for every block just to make them non-flammable...

So yeah, a filter or two for which blocks can/can't burn in general may not be a bad idea.  I'm in the middle of creating another mod right now, but after that I'll probably go through my existing mods and try to clear up some issues and suggestions

**Comment by SirAron111** [comment]
A nop i already found a work around and it all works now

**Comment by Laike-Endaril** [comment]
Oh nice, glad you found a solution! o/
