### ISSUE TITLE
Fire not spreading through walls

### ISSUE THREAD

**Issue by Foreck1** [Laike-Endaril/Controlled-Burn#6]
Would it be possible to make fire not spread through blocks? so if there's a stone wall and wood besides it, it doesn't catch fire? I have fire spread range upwards and sideways set to 4, but it just jumps "through" walls and floors

**Comment by Laike-Endaril** [comment]
This certainly makes sense, and I believe it should be doable without too much trouble.  It will probably be a global toggle if I'm successful.

**Comment by Laike-Endaril** [comment]
A config for this has been added in the latest release (in global toggles)
